### ISSUE TITLE
Tut 2: Visual Clarity

### ISSUE THREAD

**Issue by nyameko** [chpc-tech-eval/chpc24-scc-nmu#100]
Tidying up the flow and visual clarity of Tutorial 2.

**Comment by ZamaZethu** [comment]
<img width="862" alt="cluster diagram" src="https://github.com/chpc-tech-eval/chpc24-scc-nmu/assets/7393465/415a0be5-4ed2-4df4-893c-dc32f72c4ce2">

Please add this diagram for tut 2

**Comment by ZamaZethu** [comment]
Please add the ff diagram for Tut 1

<img width="664" alt="Screenshot 2024-07-06 at 21 27 16" src="https://github.com/chpc-tech-eval/chpc24-scc-nmu/assets/7393465/f5f9ea1b-8ccd-49fb-b0d2-99bbe680b1f5">

**Comment by nyameko** [comment]
hey @ZamaZethu, can you please extract images from slides and save then in a portable format, png or jpeg.
Thanks
