### ISSUE TITLE
Tut 4: Port issue around 8080, possibly changing to less popular port 8889 or something

### ISSUE THREAD

**Issue by nyameko** [chpc-tech-eval/chpc24-scc-nmu#116]
Port issue around 8080, it might be getting tarpitted after starting server.

@msovara and @smathekga, please can you test [Tutorial 4 Plotting](https://github.com/chpc-tech-eval/chpc24-scc-nmu/tree/tut3/closing_issues/tutorial4#visualize-your-hpl-benchmark-results)
* You only need a head node with an attached floating public IP
* Can one test with City Lodge WiFi and someone with Airtime / Data (Please save slips for S&T claim)

@zsanda1 please can you confirm that, port 8080 is not getting filtered after too many connection attempts.
Server starts and everything works normally, I'm able to connect and complete the tut, but after a short while, it just hangs.
* I don't know if the CHPC firewall is filter us because there are many of us connecting now from City Lodge wifi...?
* I don't know if this might be a problem tomorrow when we start the tuts with all the students...?
* Will it be difficult / take long to open port 8889 and close 8080?

@ZamaZethu  will it be a pain in the you know what, to change `scc24_sg`:
* Replace 8080 "auxiliary"
* with 8889 "jupyterlab" 

Thanks Colleagues!

**Comment by zsanda1** [comment]
If you want to change the port we can, it won't take long then you test.

**Comment by ZamaZethu** [comment]
Please change port number to 8889 for jupyterlab on tut4. you still have port 8080..

**Comment by nyameko** [comment]
@ZamaZethu thanks @zsanda1 please amend ports
