### ISSUE TITLE
Small typo in Tut1 

### ISSUE THREAD

**Issue by msovara** [chpc-tech-eval/chpc24-scc-nmu#118]
Tip

A number [encryption algorithms](https://en.wikipedia.org/wiki/Public-key_cryptography) exist for securing your SSH connections. [Elliptic Curve Digital Signature Algorithm (ECDSA)](https://en.wikipedia.org/wiki/Elliptic_Curve_Digital_Signature_Algorithm) is secure and simple enough should you need to copy the public key manually. **Nonetheless however**, you are free to use whichever algorithm you choose to.

It should be nonetheless or however.

**Comment by nyameko** [comment]
Thanks honorable member, it's been fixed!
