### ISSUE TITLE
TUT 1 - Floating IP Pool

### ISSUE THREAD

**Issue by mmhashatsi** [chpc-tech-eval/chpc24-scc-nmu#72]
Please fix the instructions for the floating ip associated

**Comment by ZamaZethu** [comment]
waiting for the network team to fix problems with the network assigned to SCC use cases, otherwise we can keep 154.114.57.0 .. I'll know the outcome today after 2pm

**Comment by ZamaZethu** [comment]
We will stick with 154.114.57.0 network for floating IPs.
