### ISSUE TITLE
TUT 1 - Troubleshooting section

### ISSUE THREAD

**Issue by mmhashatsi** [chpc-tech-eval/chpc24-scc-nmu#73]
<img width="829" alt="Screenshot 2024-07-04 at 13 32 39" src="https://github.com/chpc-tech-eval/chpc24-scc-nmu/assets/30527469/9963542e-698d-4208-b8cb-834ee1e3498d">

**Comment by ZamaZethu** [comment]
@nyameko please close this issue if you satisfied with the push I made regarding this section.

**Comment by nyameko** [comment]
@ZamaZethu  thanks for resolving this issue, and @mmhashatsi thanks for raising ut
