### ISSUE TITLE
Opening of Ports

### ISSUE THREAD

**Issue by mmhashatsi** [chpc-tech-eval/chpc24-scc-nmu#74]
Greetings all,

Theses are all the ports that are requested be open for the different service. Please ensure that the ports that you need for either your service and/or application is captured in this list

* TCP 22
* TCP 80
* TCP 443
* TCP 3000
* TCP 8080
* TCP 9090
* TCP 9100
* UDP 9993
* UDP 123
* UDP 323

**Comment by ChpcTraining** [comment]
All fine for monitoring.

**Comment by nyameko** [comment]
TCP 22 (SSH)
    TCP 80 (not used)
    TCP 443 (not used)
    TCP 3000 (Grafana)
    TCP 8080 (Auxiliary)
    TCP 9090 (Node Exporter)
    TCP 9100 (Prometheus)
    UDP 9993 (WireGuard(
    UDP 123 (Inbound NTP - Should not be necessary)
    UDP 323 (Inbound Chrony - Should not be necessary)

**Comment by ZamaZethu** [comment]
Final ports list for scc2024_sg 
TCP 22 (SSH)
TCP 3000 (Grafana)
TCP 8080 (Auxiliary)
TCP 9090 (Node Exporter)
TCP 9100 (Prometheus)
UDP 9993 (WireGuard)

**Comment by zsanda1** [comment]
Please test
