### ISSUE TITLE
TUT 1 - Upgrade danger

### ISSUE THREAD

**Issue by mmhashatsi** [chpc-tech-eval/chpc24-scc-nmu#76]
<img width="829" alt="Screenshot 2024-07-04 at 13 32 39" src="https://github.com/chpc-tech-eval/chpc24-scc-nmu/assets/30527469/8d30de9d-fbde-4bb9-a846-bd91428b1976">

Remove the upgrade command

**Comment by ZamaZethu** [comment]
upgrade replaces with update
