### ISSUE TITLE
Separate Lmod dependencies for Building Lmod or Just Using Lmod

### ISSUE THREAD

**Issue by nyameko** [chpc-tech-eval/chpc24-scc-nmu#80]
Separate git, gcc and make

from tcl and lua

**Comment by mmhashatsi** [comment]
Please also check this for Lmod

<img width="840" alt="Screenshot 2024-07-04 at 21 45 27" src="https://github.com/chpc-tech-eval/chpc24-scc-nmu/assets/30527469/bf9342c9-8859-4463-9b90-c63c9d8eb474">

**Comment by nyameko** [comment]
Closed, work around is to install Lmod from repos.
