### ISSUE TITLE
TUT 3 - HPL 

### ISSUE THREAD

**Issue by mmhashatsi** [chpc-tech-eval/chpc24-scc-nmu#81]
Please clarify this section, and add the calculator as a tip after step 5 in the HPL section

<img width="813" alt="Screenshot 2024-07-04 at 22 08 23" src="https://github.com/chpc-tech-eval/chpc24-scc-nmu/assets/30527469/2086320e-32c0-48fe-bf19-8c422d472141">

**Comment by nyameko** [comment]
done
