### ISSUE TITLE
TUT 3 - Group Install Error

### ISSUE THREAD

**Issue by mmhashatsi** [chpc-tech-eval/chpc24-scc-nmu#82]
Getting this error when trying to install these tools, this is the Building and Compiling OpenBLAS and OpenMPI Libraries from Source section

<img width="522" alt="Screenshot 2024-07-04 at 23 23 51" src="https://github.com/chpc-tech-eval/chpc24-scc-nmu/assets/30527469/9c37e664-62d8-4e68-b0ad-45da5deb4c6e">

**Comment by nyameko** [comment]
Closing

typo in original notes, changed to `sudo dnf group install "Development Tools`

**Comment by nyameko** [comment]
Development Tools

done
