### ISSUE TITLE
TUT 3 - openblas path errors

### ISSUE THREAD

**Issue by mmhashatsi** [chpc-tech-eval/chpc24-scc-nmu#86]
Here is the error and the path commands that are causing the error

<img width="896" alt="Screenshot 2024-07-05 at 00 53 16" src="https://github.com/chpc-tech-eval/chpc24-scc-nmu/assets/30527469/8a65d2ba-b568-466d-93e5-a9546318acfe">
<img width="811" alt="Screenshot 2024-07-05 at 00 53 27" src="https://github.com/chpc-tech-eval/chpc24-scc-nmu/assets/30527469/ede23980-227c-4d7a-8ab2-84870b75f6ca">

**Comment by nyameko** [comment]
Switch them around so that new mpi paths picked up first
