### ISSUE TITLE
TUT 3 - HPL Compile with IntelOpenAPI

### ISSUE THREAD

**Issue by mmhashatsi** [chpc-tech-eval/chpc24-scc-nmu#91]
I have attached a screenshot of the instructions, and the files that are in the setup 

<img width="825" alt="Screenshot 2024-07-05 at 15 22 15" src="https://github.com/chpc-tech-eval/chpc24-scc-nmu/assets/30527469/0da2d8ff-98f9-435a-91ca-4b86a128d3c3">
<img width="814" alt="Screenshot 2024-07-05 at 15 22 28" src="https://github.com/chpc-tech-eval/chpc24-scc-nmu/assets/30527469/1de3b382-ff54-4a04-a9f5-9ff036473e75">

**Comment by nyameko** [comment]
Fixed, `Make.Linux_Intel64`
